name: netket-gpu

channels:
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit-dev=11.4.*
  - cudnn=8.2.*
  - python=3.10.*
  - pip
  - jupyter
  - black
  - pip:
    - https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.3.0+cuda11.cudnn82-cp310-none-manylinux2010_x86_64.whl
    - netket